TRAINING_CONFIG_EXAMPLES = {
    "LoRA Example": {
        "summary": "LoRA 微調（單欄位模式）",
        "description": "使用 text 欄位訓練，適合一般對話數據",
        "value": {
            "model_name": "qwen3-4b-local",
            "method": "lora",
            "dataset_path": "./dataset/train.jsonl",
            "output_dir": "./output/qwen3_lora_v1",
            "text_field": "text",
            "num_train_epochs": 3,
            "per_device_train_batch_size": 2,
            "gradient_accumulation_steps": 4,
            "learning_rate": 2e-4,
            "warmup_steps": 100,
            "logging_steps": 10,
            "save_steps": 500,
            "save_total_limit": 2,
            "max_seq_length": 2048,
            "lora_r": 8,
            "lora_alpha": 16,
            "lora_dropout": 0.05,
        },
    },
    "QLoRA Example": {
        "summary": "QLoRA 微調（雙欄位模式）",
        "description": "使用 prompt + completion 訓練，適合問答對數據",
        "value": {
            "model_name": "llama3-8b-local",
            "method": "qlora",
            "dataset_path": "./dataset/qa_pairs.jsonl",
            "output_dir": "./output/llama3_qlora_qa",
            "prompt_field": "prompt",
            "completion_field": "completion",
            "num_train_epochs": 5,
            "per_device_train_batch_size": 1,
            "gradient_accumulation_steps": 8,
            "learning_rate": 1e-4,
            "warmup_steps": 50,
            "logging_steps": 5,
            "save_steps": 200,
            "save_total_limit": 3,
            "max_seq_length": 1024,
            "lora_r": 16,
            "lora_alpha": 32,
            "lora_dropout": 0.1,
        },
    },
    "Full Fine-tune with DeepSpeed": {
        "summary": "全參數微調（DeepSpeed）",
        "description": "使用 DeepSpeed offload 進行全參數微調，適合大模型",
        "value": {
            "model_name": "qwen3-4b-local",
            "method": "full",
            "dataset_path": "./dataset/train.jsonl",
            "output_dir": "./output/qwen3_full_finetune",
            "text_field": "text",
            "num_train_epochs": 2,
            "per_device_train_batch_size": 1,
            "gradient_accumulation_steps": 16,
            "learning_rate": 5e-5,
            "warmup_steps": 200,
            "logging_steps": 10,
            "save_steps": 1000,
            "save_total_limit": 1,
            "max_seq_length": 2048,
            "use_deepspeed": True,
            "deepspeed_profile": "zero3_offload_disk_disk",
        },
    },
    "LoRA with Custom DeepSpeed Config": {
        "summary": "LoRA + 自訂 DeepSpeed",
        "description": "使用自訂 DeepSpeed 配置文件",
        "value": {
            "model_name": "tinyllama-local",
            "method": "lora",
            "dataset_path": "./dataset/custom.jsonl",
            "output_dir": "./output/tinyllama_custom",
            "text_field": "content",
            "num_train_epochs": 3,
            "per_device_train_batch_size": 2,
            "gradient_accumulation_steps": 4,
            "learning_rate": 3e-4,
            "max_seq_length": 1024,
            "use_deepspeed": True,
            "deepspeed_config": "./configs/my_deepspeed_config.json",
        },
    },
}

INFERENCE_CONFIG_EXAMPLES = {
    "INT8 Quantization with CPU Offload": {
        "summary": "INT8 量化 + CPU Offload",
        "description": "使用 INT8 量化並將部分模型卸載到 CPU，適合顯存有限的情況",
        "value": {
            "model_name": "Qwen/Qwen3-4B",
            "quantization": "int8",
            "model_total_memory": "10GB",
            "device_map": "auto",
            "max_memory": {"0": "5GB", "cpu": "5GB"},
            "torch_dtype": "auto",
        },
    },
    "CPU Only Execution": {
        "summary": "純 CPU 執行",
        "description": "完全在 CPU 上運行模型，速度較慢但無需 GPU",
        "value": {
            "model_name": "Qwen/Qwen3-4B",
            "quantization": "none",
            "model_total_memory": "15GB",
            "device_map": "cpu",
        },
    },
    "Large Model with Disk Offload": {
        "summary": "大模型 + Disk Offload",
        "description": "運行超大模型，同時使用 CPU 和 Disk Offload",
        "value": {
            "model_name": "openai/gpt-oss-120b",
            "quantization": "int8",
            "model_total_memory": "120GB",
            "device_map": "auto",
            "max_memory": {"0": "5GB", "cpu": "20GB"},
            "offload_folder": "./offload",
        },
    },
    "Llama Server Engine": {
        "summary": "Llama Server (多人並發)",
        "description": "透過 load/unload 動態啟停 llama-server 子程序，並支援 -np 多槽位併發",
        "value": {
            "model_name": "Qwen/Qwen3-4B",
            "model_path": "/path/to/model.gguf",
            "engine": "llama_server",
            "llama_server_auto_start": True,
            "llama_server_binary": "llama-server",
            "llama_server_host": "127.0.0.1",
            "llama_server_port": 8080,
            "llama_server_np": 4,
            "llama_server_health_timeout": 300,
            "llama_server_url": "http://127.0.0.1:8080",
            "llama_server_model": "Qwen/Qwen3-4B",
            "llama_server_mmproj": "/path/to/mmproj.gguf",
            "llama_server_timeout": 300,
            "n_gpu_layers": -1,
            "n_ctx": 4096,
            "n_batch": 512,
        },
    },
    "vLLM Engine": {
        "summary": "vLLM OpenAI-compatible Server",
        "description": "由後端在 load_model 時啟動 vLLM server，unload_model 時停止",
        "value": {
            "model_name": "Qwen/Qwen3-4B",
            "engine": "vllm",
            "vllm_gpu_memory_utilization": 0.8,
            "vllm_max_model_len": 4096,
            "vllm_enforce_eager": False,
            "vllm_cpu_offload_gb": 8,
        },
    },
    "Intel XPU (Intel GPU)": {
        "summary": "Intel XPU 推理",
        "description": "使用 Intel GPU (Arc/Iris Xe) 進行推理，支援 INT8 量化",
        "value": {
            "model_name": "Qwen/Qwen3-4B",
            "quantization": "int8",
            "model_total_memory": "10GB",
            "device_map": "auto",
            "max_memory": {"xpu:0": "6GB", "cpu": "8GB"},
            "torch_dtype": "auto",
        },
    },
    "Intel XPU Multi-Device": {
        "summary": "Intel XPU 多卡",
        "description": "使用多張 Intel GPU 進行推理（混合 offload）",
        "value": {
            "model_name": "Qwen/Qwen3-8B",
            "quantization": "int4",
            "model_total_memory": "20GB",
            "device_map": "auto",
            "max_memory": {
                "xpu:0": "8GB",
                "xpu:1": "8GB",
                "cpu": "16GB"
            },
            "torch_dtype": "auto",
        },
    },
    "Intel XPU Pure mode": {
        "summary": "純 XPU 模式（不使用 CPU offload）",
        "description": "完全在 Intel GPU 上運行，適合顯存充足的情況",
        "value": {
            "model_name": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
            "quantization": "int4",
            "device_map": "auto",
            "max_memory": {"xpu:0": "12GB"},
            "torch_dtype": "float16",
        },
    },
}

MEMORY_ESTIMATE_EXAMPLES = {
    "Standard Estimation": {
        "summary": "標準估計 (FP16)",
        "description": "估計 4B 模型在 FP16 下的記憶體需求",
        "value": {
            "model_name": "Qwen/Qwen3-4B",
            "quantization": "none",
            "batch_size": 1,
            "sequence_length": 2048,
        },
    },
    "INT8 Estimation": {
        "summary": "INT8 量化估計",
        "description": "估計 1.1B 模型在 INT8 量化下的記憶體需求",
        "value": {
            "model_name": "TinyLlama/TinyLlama-1.1B-Chat-v1.0",
            "quantization": "int8",
            "batch_size": 1,
            "sequence_length": 4096,
        },
    },
}

CONVERSION_CONFIG_EXAMPLES = {
    "Auto Detect (Recommended)": {
        "summary": "自動判斷輸出類型",
        "description": "優先使用 `auto`，讓 llama.cpp 依模型權重自動選擇常見的 16-bit 類型。",
        "value": {
            "model_path": "/path/to/hf-or-merged-model",
            "output_path": "/path/to/output/model-auto.gguf",
            "outtype": "auto",
        },
    },
    "F16 Common": {
        "summary": "F16 半精度",
        "description": "最常見的完整模型 GGUF 類型之一，通常在容量與相容性之間取得平衡。",
        "value": {
            "model_path": "/path/to/hf-or-merged-model",
            "output_path": "/path/to/output/model-f16.gguf",
            "outtype": "f16",
        },
    },
    "BF16 Common": {
        "summary": "BF16 半精度",
        "description": "適合原始權重本身為 bfloat16 的模型，例如你目前的 Qwen3.5 權重。",
        "value": {
            "model_path": "/path/to/hf-or-merged-model",
            "output_path": "/path/to/output/model-bf16.gguf",
            "outtype": "bf16",
        },
    },
    "Q8_0 Quantized": {
        "summary": "Q8_0 量化",
        "description": "常見的高品質量化格式，檔案比 F16/BF16 小，但仍保有不錯精度。",
        "value": {
            "model_path": "/path/to/hf-or-merged-model",
            "output_path": "/path/to/output/model-q8_0.gguf",
            "outtype": "q8_0",
        },
    },
    "F32 Full Precision": {
        "summary": "F32 全精度",
        "description": "體積最大，通常只在除錯、驗證或特定精度需求時使用。",
        "value": {
            "model_path": "/path/to/hf-or-merged-model",
            "output_path": "/path/to/output/model-f32.gguf",
            "outtype": "f32",
        },
    },
}
